# Используем официальный образ Node.js версии 20
FROM node:20.18.0

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости проекта
RUN npm i

# Устанавливаем nodemon
RUN npm install -g nodemon

# Копируем все файлы проекта
COPY . .

# Запускаем приложение
CMD ["npm", "run", "dev"]
